## References:

1. Higher-order multivariate Markov chains and their applications; Wai-Ki Ching , Michael K.Ng , Eric S.Fungb, 2008

=>Implementationa and usage example shown here

2. A multivariate Markov chain model for categorical data sequences and its applications in demand predictions
   Wai‐Ki Ching  Eric S. Fung  Michael K. Ng
    

3. Higher-Order Markov Chain Models for Categorical Data Sequences* Wai Ki Ching, Eric S. Fung, Michael K. Ng [Implemented here as WeightedMarkov]

0. <a src="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjM66WC3JbXAhVil1QKHTj1CakQFggtMAA&url=http%3A%2F%2Fwww.ccsenet.org%2Fjournal%2Findex.php%2Fmas%2Farticle%2FviewFile%2F6040%2F4874_1_1_1&usg=AOvVaw0fZh5XmtYpF14lVZRfr6aZ">  Application of Markov Chains to Analyze and Predict the Time Series </a>


In [149]:
import numpy as np;
import pandas as pd;
import importlib
import numpy as np
from collections import defaultdict
from WeightedMarkov.NaiveMarkov import *
from WeightedMarkov.WeightedHOMVMarkov import *


In [150]:
s1 = [2,1,3,3,4,3,2,1,3,3,2,1]
s1 = [1,0,2,2,3,2,1,0,2,2,1,0]
s2 = [2,4,4,4,4,2,3,3,1,4,3,3]
s2 = [1,3,3,3,3,1,2,2,0,3,2,2]
X=[s1,s2]
order = 2
n=2       # => order
s=len(X)  # => Number of series
hm = WeightedHOMVMarkov(X,4, order)
f, p, x = hm.fit();
#dumps=hm.Dump()

c,A,b = hm.PrepareMatrices()
hm.DisplayCAb(0)
# => One is good - uncomment to see the other CAB too
#hm.DisplayCAb(1)
#print ("c=", c, "\nA=\n", A, "\nb=", b)
sol = hm.Solve(False)
hm.DumpSolution()
for i,s in enumerate(hm.sol):
    print("X_({}) => ".format(i), end='')
    for f in np.array([_ for _ in sol[i]['x'].T][:-1]):
        print("{0:.4f}".format(f), end=' ' )
    print()


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

X_(0) => 0.0948 0.0310 0.8431 0.0310 
X_(1) => 0.2000 0.2000 0.6000 0.0000 


In [151]:
hm.SelfEval();


0 [ 0.0155  0.1686  0.6472  0.1686] 2 2
1 [ 0.2   0.12  0.12  0.56] 3 3
=======================Metrics :  None
orig=>[2 2 2 2 1 0 0 2 2 0]
pred=>[2, 2, 3, 2, 1, 0, 2, 2, 1, 0]
Total 10, correct 7, acc: 70.00 %
class: 0 total: 3, correct: 2, accuracy: 0.6666666666666666
class: 1 total: 1, correct: 1, accuracy: 1.0
class: 2 total: 6, correct: 4, accuracy: 0.6666666666666666
=======================Metrics :  None
orig=>[3 3 3 3 2 2 2 3 3 2]
pred=>[3, 3, 3, 1, 2, 2, 0, 3, 2, 2]
Total 10, correct 7, acc: 70.00 %
class: 2 total: 4, correct: 3, accuracy: 0.75
class: 3 total: 6, correct: 4, accuracy: 0.6666666666666666


## Example  from Reference [1]

In [152]:
ProductA=" 6 6 6 6 2 6 2 6 2 2 6 2 6 6 2 6 2 4 4 4 5 6 6 1 2 2 6 6 6 2 6 2 6 6 2 6 2 2 6 2 1 2 2 6 6 6 2 1262662262226262222262266661226222262222332326666262662 6266266223433131216166166262622266162612162622226616622 62223444646166166661622266662662262622262226666322622222 26262226226626662223334166166161666616662122222236666626"
ProductB=" 1 6 6 1 6 1 1 1 1 1 1 6 6 6 1 2 1 6 6 1 1 1 6 6 2 1 6 6 1 1 1 6 1 2 1 6 2 2 2 2 2 6 1 6 6 1 2 1666111661111611216161162626663661662223226661162662626 6136611122322622216161162111221611112611116161216166161 22223322266662116111616161611662116611262666126161111616 11661661616611662222222226666166616616611613335166666666"
ProductC=" 6 6 6 6 6 6 6 2 6 6 6 6 6 6 6 2 6 6 6 6 2 6 6 6 2 2 6 6 6 6 6 6 6 1 6 2 6 6 6 6 6 6 6 6 2 6 6 1261661626666666266626616666666336321221661616666661666 1666666666662666666662266261266626626626162621266226262 26266622266266226121266226612216262211563616612261626616 26266616166222123616161616661166666166616116666666616616"
ProductD=" 6 2 2 2 2 3 3 4 4 4 5 4 3 3 6 2 6 6 6 3 4 4 3 3 3 3 3 2 6 6 3 4 4 4 4 3 4 2 6 2 2 6 2 2 6 6 3 4544636662626622644543434462662262662662662626355544436 2662626226266264444446366262626266222222222333554533362 66226222262322363223444455446626262222222554455262662626 22334454443436262222222222234444544432226222626262222232"
ProductE=" 6 2 2 2 2 3 3 4 4 4 5 4 3 3 6 2 6 6 2 3 4 4 3 4 4 3 3 2 2 6 3 4 4 4 4 3 4 2 3 2 2 6 3 3 6 6 3 4545332662626622644444454462662262662662662626344444446 2662626666262264444446336222626222222222222364555524662 66226222262322363223444455433626222632222554444362662626 22334454444436262226222222234444544432226662626262222222"

pA=[int(c) - 1 for c in ProductA if c != ' ']
pB=[int(c) - 1 for c in ProductB if c != ' ']
pC=[int(c) - 1 for c in ProductC if c != ' ']
pD=[int(c) - 1 for c in ProductD if c != ' ']
pE=[int(c) - 1 for c in ProductE if c != ' ']
X=[pA,pB,pC,pD,pE]
    
order = 8
n=6       # => number of States
s=len(X)  # => Number of series

hm = WeightedHOMVMarkov(X, n, order)
f, p, x = hm.fit();
#h.Dump()
c,A,b = hm.PrepareMatrices()
#hm.DisplayCAb(0)
#hm.DisplayCAb(1)
#print ("c=", c, "\nA=\n", A, "\nb=", b)
sol = hm.Solve(False)
hm.DumpSolution();

#for i,s in enumerate(hm.sol):
#    print("X_({}) => ".format(i), end='')
#    for f in np.array([_ for _ in sol[i]['x'].T][:-1]):
#        print("{0:.4f}".format(f), end=' ' )
#    print()
    

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [153]:
ac=hm.SelfEval();

0 [ 0.0606  0.4444  0.0101  0.0101  0.0101  0.4646] 5 1
1 [ 0.404   0.1368  0.0239  0.      0.      0.4353] 5 0
2 [ 0.1639  0.2295  0.      0.      0.      0.6066] 5 5
3 [ 0.      0.2145  0.1397  0.3594  0.1184  0.1679] 3 3
4 [ 0.      0.1324  0.1348  0.5013  0.1321  0.0995] 3 3
=======================Metrics :  None
orig=>[5 5 5 5 5 5 5 5 1 5 5 5 5 5 5 5 5 1 5 5 5 5 5 5 5 5 1 5 5 1 1 1 1 1 5 5 5 5 5 1 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 1 5 5 5 5 5 5 5 1 5 1 5 5 5 1 5 5 5 5 5 1 1 1 1]
pred=>[1, 1, 5, 1, 5, 5, 1, 5, 1, 3, 3, 3, 4, 5, 5, 0, 1, 1, 5, 5, 5, 1, 5, 1, 5, 5, 1, 5, 1, 1, 5, 1, 0, 1, 1, 5, 5, 5, 1, 0, 1, 5, 1, 5, 5, 1, 1, 5, 1, 1, 1, 5, 1, 5, 1, 1, 1, 1, 1, 5, 1, 1, 5, 5, 5, 5, 0, 1, 1, 5, 1, 1, 1, 1, 5, 1, 1, 1, 1, 2]
Total 261, correct 129, acc: 49.43 %
class: 1 total: 63, correct: 30, accuracy: 0.47619047619047616
class: 5 total: 198, correct: 99, accuracy: 0.5
=======================Metrics :  None
orig=>[5 5 5 5 0 0 0 5 1 5 5 0 5 5 5 0 0 1 5 5 0 5 5 5 0 5 1 5 5 1 1 1 1 1 5 5 

In [154]:
def approx(i,n, eps=0.000001):
    ret = abs(n - i) <= eps
    return ret;

def StationaryDist(k, printOut=True):
    k = np.matrix(k)
    eigenvalues, eigenvectors = np.linalg.eig(k)
    ev, et = eigenvalues, eigenvectors
    colSumsK = k.sum(axis=0)

    if(any([not approx(c,1) for c in colSumsK.flat])):
        print("Columns sums !=1 - not a suitable Trans Matrix: taking Transpose")
        k = k.T
        colSums1 = k.sum(axis=0)
        if(any([not approx(c,1) for c in colSums1.flat])):
            print("Columns sums !=1 - not a suitable Trans Matrix")
            return colSums
    
    eigenvalues, eigenvectors = np.linalg.eig(k)
    ev, et = eigenvalues, eigenvectors
    evl = np.argmax(ev)
    evt = et[:,evl]
    evr = evt/evt.sum(axis=0)
    
    stationatyDist = evt
    stationaryPI = evr
    
    colSums = et.sum(axis=0)
    test=k * evr

    if (printOut):
        print("Eigen Values/Vectors of\n{}\n{}\n=EV:{}\n{}\n".format( k, colSumsK, ev, et))
        print("index={} Stat Disy:\n{} \nStatPI:\n{}\n{})".format( evl, stationatyDist.T, stationaryPI.T, test) )
    
    return stationatyDist, stationaryPI

#k=np.matrix([[0.5,.5,0], [0.25,0.5,0.25],[0,0.5,0.5]]).T
k=hm.pS[(1,1,1)]
d,v=StationaryDist(k);

Eigen Values/Vectors of
[[ 0.      0.0459  0.1538  0.1111  0.      0.1228]
 [ 0.3182  0.4679  0.2308  0.      0.      0.4211]
 [ 0.0455  0.055   0.3077  0.1111  0.      0.0088]
 [ 0.      0.0092  0.2308  0.4444  0.      0.0088]
 [ 0.      0.      0.      0.1111  0.      0.    ]
 [ 0.6364  0.422   0.0769  0.2222  1.      0.4386]]
[[ 1.  1.  1.  1.  1.  1.]]
=EV:[ 1.      0.4845  0.2819 -0.1542 -0.0016  0.0481]
[[ 0.1375 -0.066  -0.0709  0.5888 -0.6736  0.4502]
 [ 0.6811  0.7686  0.7679  0.2464  0.6598 -0.7877]
 [ 0.0812 -0.1382  0.2506 -0.0822 -0.0109  0.0943]
 [ 0.0562 -0.586  -0.3763  0.0391 -0.0036 -0.0454]
 [ 0.0062 -0.1344 -0.1483 -0.0282  0.249  -0.1049]
 [ 0.7123  0.1559 -0.423  -0.7639 -0.2208  0.3934]]

index=0 Stat Disy:
[[ 0.1375  0.6811  0.0812  0.0562  0.0062  0.7123]] 
StatPI:
[[ 0.0821  0.4067  0.0485  0.0336  0.0037  0.4254]]
[[ 0.0821]
 [ 0.4067]
 [ 0.0485]
 [ 0.0336]
 [ 0.0037]
 [ 0.4254]])
