In [17]:
import numpy as np;
from collections import defaultdict

import pandas as pd;
import importlib
import sys

from WeightedMarkov.WeightedMarkov import *
from WeightedMarkov.NaiveMarkov import *
#Call delModules before reimporting to fresh imported classes
def delModules(mod):
    mods = []
    for c,md in enumerate(sys.modules): 
        if (md == mod or md.startswith(mod+".") ):
            #print("Delete: " , md)
            mods += [md]
    for m in sorted(mods):
        del sys.modules[m]

delModules("WeightedMarkov")
from WeightedMarkov.NaiveMarkov import *
from WeightedMarkov.WeightedMarkov import *


In [19]:
s1=[int(_) for _ in '0 0 1 1 0 2 1 0 1 2 0 1 2 0 1 2 0 1 0 1'.split()]
numClasses = len(np.unique(s1))
X=[s1]
order=2
m= numClasses
hm= WeightedMarkov(X,m, order)
fS,pS, xHats = hm.fit(X)

print("==>Show the results are as expected when setup right")
c,A,b = hm.PrepareMatrices()
sol = hm.Solve(False)

hm.Dump()

==>Show the results are as expected when setup right


<IPython.core.display.Math object>

## References:

1. <a src="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjM66WC3JbXAhVil1QKHTj1CakQFggtMAA&url=http%3A%2F%2Fwww.ccsenet.org%2Fjournal%2Findex.php%2Fmas%2Farticle%2FviewFile%2F6040%2F4874_1_1_1&usg=AOvVaw0fZh5XmtYpF14lVZRfr6aZ">  Application of Markov Chains to Analyze and Predict the Time Series </a>

2. A multivariate Markov chain model for categorical data sequences and its applications in demand predictions
   Wai‐Ki Ching  Eric S. Fung  Michael K. Ng
    
3. Higher-order multivariate Markov chains and their applications; Wai-Ki Ching , Michael K.Ng , Eric S.Fungb

4. Higher-Order Markov Chain Models for Categorical Data Sequences* Wai Ki Ching, Eric S. Fung, Michael K. Ng [Implemented here as WeightedMarkov]


In [20]:
print ('''
****************** TESTING/USAGE oF NAIE MARKOV CHAIN ****************
*
''')

s1=[int(_) for _ in '0 0 1 1 0 2 1 0 1 2 0 1 2 0 1 2 0 1 0 1'.split()]
numClasses = len(np.unique(s1))
print("# Try the Naive Markov Chain Approach ............For Paper Example")

order = 1
m=NaiveMarkov(' ', order)
m.fit(s1)
start = tuple([s1[i] for i in range(order)])
r = m.Predict(start )
NaiveMarkov.Score(s1, r, True, msg="For MC order = {}".format(order))
r = m.PredictFromList(s1 )
NaiveMarkov.Score(s1, r, msg="For MC: with seeds taken from original fit tuples");


order=3
m=NaiveMarkov(' ', order)
m.fit(s1[:-6])
start = tuple([s1[i] for i in range(order)])
r = m.Predict(start )
NaiveMarkov.Score(s1, r, True, msg="For MC order = {}".format(order))

r = m.PredictFromList(s1 )
NaiveMarkov.Score(s1, r, msg="For MC: with seeds taken from original fitted tuples");
#Metrics(s1, r)
#F,p = NaiveMarkov.Freq(s1)



****************** TESTING/USAGE oF NAIE MARKOV CHAIN ****************
*

# Try the Naive Markov Chain Approach ............For Paper Example
=======================Metrics :  For MC order = 1
orig=>[0, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1]
pred=>[0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1]
Total 20, correct 6, acc: 0.30
class:0 total:8, correct:1, accuracy:0.125
class:1 total:8, correct:5, accuracy:0.625
class:2 total:4, correct:0, accuracy:0.0
=======================Metrics :  For MC: with seeds taken from original fit tuples
orig=>[0, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1]
pred=>[0, 2, 1, 2, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 2, 2, 0, 1, 2, 1]
Total 20, correct 11, acc: 0.55
class:0 total:8, correct:5, accuracy:0.625
class:1 total:8, correct:5, accuracy:0.625
class:2 total:4, correct:1, accuracy:0.25
=======================Metrics :  For MC order = 3
orig=>[0, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1]
pred=>[1, 0, 0,

In [21]:
# Paper Example - lets prove the examples in paper works correctly!

s1=[int(_) for _ in '0 0 1 1 0 2 1 0 1 2 0 1 2 0 1 2 0 1 0 1'.split()]
numClasses = len(np.unique(s1))
print( '''# Lets try the Weighted  Markov Chain Approach ............
Lets make sure the numbers are as given in the paper''')

X=[s1]

order=2
m= numClasses
hm= WeightedMarkov(X,m, order)
fS,pS, xHats = hm.fit(X)

print("==>Show if we remove non negative constraints - the results are as expected")
c,A,b = hm.PrepareMatricesNN()
sol = hm.Solve(False)
params = np.array([_ for _ in sol['x'].T])
soltn = sum(np.array(c) * sol['x'])
print("LP Solutions non -ve constraint...\n\n", params, sum(params[0:2]), "solution=", soltn)

print("==>Show the results are as expected when setup right")
c,A,b = hm.PrepareMatrices()
sol = hm.Solve(False)

hm.Dump()
print("LP Setup ...")
hm.DisplayCAb()
soltn = sum(np.array(c) * sol['x'])
params = np.array([_ for _ in sol['x'].T])
print("LP Solved Solutions ....\n", params, sum(params[0:2]), "solution=", soltn)



# Lets try the Weighted  Markov Chain Approach ............
Lets make sure the numbers are as given in the paper
==>Show if we remove non negative constraints - the results are as expected
LP Solutions non -ve constraint...

 [ 1.8    -0.8     0.0157] 0.99999999995 solution= [ 0.      0.      1.0157]
==>Show the results are as expected when setup right


<IPython.core.display.Math object>

LP Setup ...


<IPython.core.display.Math object>

LP Solved Solutions ....
 [  1.0000e+00   2.4360e-08   2.8571e-02] 1.00000000214 solution= [ 0.      0.      1.0286]


In [22]:
# This is to show the rules if Xt=1, Xt+1 = 2; etc 
#
#
from copy import deepcopy

# You can adjust for floating point/round off errors by uncommenting following two lines
#hm.p[0]=1
#hm.p[1]=0

m= len(unique(s1))
XX=[0 for _ in range(m)]
XC=[XX.copy() for _ in range(order)]

for j in it.product(range(m), repeat=order):
    Xt = deepcopy(XC); #.copy()
    for i,c in enumerate(j): 
        Xt[i][c]= 1

    r,p=hm.Predict(Xt)
    
    print(j, p, Xt, r.T, r.flat[0], r.flat[1], r.flat[2])


(0, 0) 1 [[1, 0, 0], [1, 0, 0]] [[ 0.125  0.75   0.125]] 0.125000000702 0.749999993773 0.125000007662
(0, 1) 1 [[1, 0, 0], [0, 1, 0]] [[ 0.125  0.75   0.125]] 0.125000011142 0.749999990293 0.125000000702
(0, 2) 1 [[1, 0, 0], [0, 0, 1]] [[ 0.125  0.75   0.125]] 0.125000003312 0.750000001603 0.124999997222
(1, 0) 2 [[0, 1, 0], [1, 0, 0]] [[ 0.4286  0.1429  0.4286]] 0.428571422527 0.142857150122 0.428571429487
(1, 1) 0 [[0, 1, 0], [0, 1, 0]] [[ 0.4286  0.1429  0.4286]] 0.428571432967 0.142857146642 0.428571422527
(1, 2) 0 [[0, 1, 0], [0, 0, 1]] [[ 0.4286  0.1429  0.4286]] 0.428571425137 0.142857157952 0.428571419047
(2, 0) 0 [[0, 0, 1], [1, 0, 0]] [[  7.5000e-01   2.5000e-01   1.0440e-08]] 0.749999986813 0.250000004884 1.04398746163e-08
(2, 1) 0 [[0, 0, 1], [0, 1, 0]] [[  7.5000e-01   2.5000e-01   3.4800e-09]] 0.749999997253 0.250000001404 3.47995820543e-09
(2, 2) 0 [[0, 0, 1], [0, 0, 1]] [[ 0.75  0.25  0.  ]] 0.749999989423 0.250000012714 0.0


In [23]:
#This section is to actually do the prediction on the given set: 12/19 Proof
pdt = [s1[order-1]]
print("=>", s1)

for j in range(len(s1) - order):
    Xt = deepcopy(XC); #.copy()
#    for i in range(order):
#        Xt[i][s1[j+i]]=1
    prs=[0 for _ in range(order)]
    for i,c in enumerate(reversed(s1[j:j+order]) ):
        prs[i] = c;
        Xt[i][c]=1
        
    r, predicted = hm.Predict(Xt)

    original  = s1[j+order]
    pdt.append(predicted)
    
    print("{} {}=>{} {} {} {}".format(prs, original, predicted,j, Xt, r.T) )
    #if( j==2): break
    
NaiveMarkov.Score(s1[order:], pdt[1:])

=> [0, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1]
[0, 0] 1=>1 0 [[1, 0, 0], [1, 0, 0]] [[ 0.125  0.75   0.125]]
[1, 0] 1=>2 1 [[0, 1, 0], [1, 0, 0]] [[ 0.4286  0.1429  0.4286]]
[1, 1] 0=>0 2 [[0, 1, 0], [0, 1, 0]] [[ 0.4286  0.1429  0.4286]]
[0, 1] 2=>1 3 [[1, 0, 0], [0, 1, 0]] [[ 0.125  0.75   0.125]]
[2, 0] 1=>0 4 [[0, 0, 1], [1, 0, 0]] [[  7.5000e-01   2.5000e-01   1.0440e-08]]
[1, 2] 0=>0 5 [[0, 1, 0], [0, 0, 1]] [[ 0.4286  0.1429  0.4286]]
[0, 1] 1=>1 6 [[1, 0, 0], [0, 1, 0]] [[ 0.125  0.75   0.125]]
[1, 0] 2=>2 7 [[0, 1, 0], [1, 0, 0]] [[ 0.4286  0.1429  0.4286]]
[2, 1] 0=>0 8 [[0, 0, 1], [0, 1, 0]] [[  7.5000e-01   2.5000e-01   3.4800e-09]]
[0, 2] 1=>1 9 [[1, 0, 0], [0, 0, 1]] [[ 0.125  0.75   0.125]]
[1, 0] 2=>2 10 [[0, 1, 0], [1, 0, 0]] [[ 0.4286  0.1429  0.4286]]
[2, 1] 0=>0 11 [[0, 0, 1], [0, 1, 0]] [[  7.5000e-01   2.5000e-01   3.4800e-09]]
[0, 2] 1=>1 12 [[1, 0, 0], [0, 0, 1]] [[ 0.125  0.75   0.125]]
[1, 0] 2=>2 13 [[0, 1, 0], [1, 0, 0]] [[ 0.4286  0.1429  0

(18, 14, defaultdict(int, {0: 6, 1: 8, 2: 4}))

In [25]:
import numpy as np;

j=np.zeros((3*(2+1)))
j=j.reshape(3,2+1)
j[:,-1]=1
for k in range(2):        
    pd1 = hm.pS.get(k)
    xh1 = hm.xHats[0]
    bb1 = pd1 * xh1
    j[:,k] = bb1.flatten()
    print(pd1, xh1, bb1)
    
j

[[ 0.125   0.4286  0.75  ]
 [ 0.75    0.1429  0.25  ]
 [ 0.125   0.4286  0.    ]] [[ 0.4]
 [ 0.4]
 [ 0.2]] [[ 0.3714]
 [ 0.4071]
 [ 0.2214]]
[[ 0.1429  0.5714  0.25  ]
 [ 0.4286  0.2857  0.75  ]
 [ 0.4286  0.1429  0.    ]] [[ 0.4]
 [ 0.4]
 [ 0.2]] [[ 0.3357]
 [ 0.4357]
 [ 0.2286]]


array([[ 0.3714,  0.3357,  1.    ],
       [ 0.4071,  0.4357,  1.    ],
       [ 0.2214,  0.2286,  1.    ]])